title = "Web Performance"
baseURL = "https://docs.snowplow.io/accelerators/web_performance/"

[params]
  description = "Tutorial for setting up web performance tracking for your website"
  author = "Agness Kiss, Peter Perlepes"
